//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./translit_types');
//HELPER FUNCTIONS AND STRUCTURES

var translit_svc_get_str_args = function(args) {
  this.str = null;
  this.lang = null;
  if (args) {
    if (args.str !== undefined && args.str !== null) {
      this.str = args.str;
    }
    if (args.lang !== undefined && args.lang !== null) {
      this.lang = args.lang;
    }
  }
};
translit_svc_get_str_args.prototype = {};
translit_svc_get_str_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.str = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.lang = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

translit_svc_get_str_args.prototype.write = function(output) {
  output.writeStructBegin('translit_svc_get_str_args');
  if (this.str !== null && this.str !== undefined) {
    output.writeFieldBegin('str', Thrift.Type.STRING, 1);
    output.writeString(this.str);
    output.writeFieldEnd();
  }
  if (this.lang !== null && this.lang !== undefined) {
    output.writeFieldBegin('lang', Thrift.Type.STRING, 2);
    output.writeString(this.lang);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var translit_svc_get_str_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
translit_svc_get_str_result.prototype = {};
translit_svc_get_str_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

translit_svc_get_str_result.prototype.write = function(output) {
  output.writeStructBegin('translit_svc_get_str_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var translit_svcClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
translit_svcClient.prototype = {};
translit_svcClient.prototype.seqid = function() { return this._seqid; };
translit_svcClient.prototype.new_seqid = function() { return this._seqid += 1; };
translit_svcClient.prototype.get_str = function(str, lang, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get_str(str, lang);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get_str(str, lang);
  }
};

translit_svcClient.prototype.send_get_str = function(str, lang) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_str', Thrift.MessageType.CALL, this.seqid());
  var params = {
    str: str,
    lang: lang
  };
  var args = new translit_svc_get_str_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

translit_svcClient.prototype.recv_get_str = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new translit_svc_get_str_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_str failed: unknown result');
};
var translit_svcProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
translit_svcProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
translit_svcProcessor.prototype.process_get_str = function(seqid, input, output) {
  var args = new translit_svc_get_str_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get_str.length === 2) {
    Q.fcall(this._handler.get_str.bind(this._handler), args.str, args.lang)
      .then(function(result) {
        var result_obj = new translit_svc_get_str_result({success: result});
        output.writeMessageBegin("get_str", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_str", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get_str(args.str, args.lang, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new translit_svc_get_str_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("get_str", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_str", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
